var annotated_dup =
[
    [ "GFt", "namespace_g_ft.html", [
      [ "json", "namespace_g_ft_1_1json.html", [
        [ "Format", "struct_g_ft_1_1json_1_1_format.html", "struct_g_ft_1_1json_1_1_format" ],
        [ "Value", "class_g_ft_1_1json_1_1_value.html", "class_g_ft_1_1json_1_1_value" ]
      ] ],
      [ "UI", "namespace_g_ft_1_1_u_i.html", [
        [ "XBlock", "struct_g_ft_1_1_u_i_1_1_x_block.html", "struct_g_ft_1_1_u_i_1_1_x_block" ],
        [ "XButton", "struct_g_ft_1_1_u_i_1_1_x_button.html", "struct_g_ft_1_1_u_i_1_1_x_button" ],
        [ "XCheckBox", "struct_g_ft_1_1_u_i_1_1_x_check_box.html", "struct_g_ft_1_1_u_i_1_1_x_check_box" ],
        [ "XColumnLayout", "struct_g_ft_1_1_u_i_1_1_x_column_layout.html", "struct_g_ft_1_1_u_i_1_1_x_column_layout" ],
        [ "XGridLayout", "struct_g_ft_1_1_u_i_1_1_x_grid_layout.html", "struct_g_ft_1_1_u_i_1_1_x_grid_layout" ],
        [ "XHSlider", "struct_g_ft_1_1_u_i_1_1_x_h_slider.html", "struct_g_ft_1_1_u_i_1_1_x_h_slider" ],
        [ "XLabel", "struct_g_ft_1_1_u_i_1_1_x_label.html", "struct_g_ft_1_1_u_i_1_1_x_label" ],
        [ "XMainWindow", "struct_g_ft_1_1_u_i_1_1_x_main_window.html", "struct_g_ft_1_1_u_i_1_1_x_main_window" ],
        [ "XRadioBox", "struct_g_ft_1_1_u_i_1_1_x_radio_box.html", "struct_g_ft_1_1_u_i_1_1_x_radio_box" ],
        [ "XRowLayout", "struct_g_ft_1_1_u_i_1_1_x_row_layout.html", "struct_g_ft_1_1_u_i_1_1_x_row_layout" ],
        [ "XVSlider", "struct_g_ft_1_1_u_i_1_1_x_v_slider.html", "struct_g_ft_1_1_u_i_1_1_x_v_slider" ],
        [ "XWindow", "struct_g_ft_1_1_u_i_1_1_x_window.html", "struct_g_ft_1_1_u_i_1_1_x_window" ]
      ] ],
      [ "Widget", "namespace_g_ft_1_1_widget.html", [
        [ "Button", "class_g_ft_1_1_widget_1_1_button.html", "class_g_ft_1_1_widget_1_1_button" ],
        [ "CheckBox", "class_g_ft_1_1_widget_1_1_check_box.html", "class_g_ft_1_1_widget_1_1_check_box" ],
        [ "HScrollBar", "class_g_ft_1_1_widget_1_1_h_scroll_bar.html", "class_g_ft_1_1_widget_1_1_h_scroll_bar" ],
        [ "HSlider", "class_g_ft_1_1_widget_1_1_h_slider.html", "class_g_ft_1_1_widget_1_1_h_slider" ],
        [ "Label", "class_g_ft_1_1_widget_1_1_label.html", "class_g_ft_1_1_widget_1_1_label" ],
        [ "MainWindow", "class_g_ft_1_1_widget_1_1_main_window.html", "class_g_ft_1_1_widget_1_1_main_window" ],
        [ "RadioBox", "class_g_ft_1_1_widget_1_1_radio_box.html", "class_g_ft_1_1_widget_1_1_radio_box" ],
        [ "VScrollBar", "class_g_ft_1_1_widget_1_1_v_scroll_bar.html", "class_g_ft_1_1_widget_1_1_v_scroll_bar" ],
        [ "VSlider", "class_g_ft_1_1_widget_1_1_v_slider.html", "class_g_ft_1_1_widget_1_1_v_slider" ]
      ] ],
      [ "Animation", "class_g_ft_1_1_animation.html", "class_g_ft_1_1_animation" ],
      [ "AnimationAbstract", "class_g_ft_1_1_animation_abstract.html", "class_g_ft_1_1_animation_abstract" ],
      [ "AnimationManager", "class_g_ft_1_1_animation_manager.html", "class_g_ft_1_1_animation_manager" ],
      [ "AnimationParams", "struct_g_ft_1_1_animation_params.html", "struct_g_ft_1_1_animation_params" ],
      [ "AnimationPause", "class_g_ft_1_1_animation_pause.html", "class_g_ft_1_1_animation_pause" ],
      [ "AnimationPlay", "class_g_ft_1_1_animation_play.html", "class_g_ft_1_1_animation_play" ],
      [ "AnimationState", "class_g_ft_1_1_animation_state.html", "class_g_ft_1_1_animation_state" ],
      [ "AnimationStop", "class_g_ft_1_1_animation_stop.html", "class_g_ft_1_1_animation_stop" ],
      [ "Application", "class_g_ft_1_1_application.html", "class_g_ft_1_1_application" ],
      [ "Bezier", "class_g_ft_1_1_bezier.html", "class_g_ft_1_1_bezier" ],
      [ "Block", "class_g_ft_1_1_block.html", "class_g_ft_1_1_block" ],
      [ "BlockFocusManager", "class_g_ft_1_1_block_focus_manager.html", null ],
      [ "BlockHoverManager", "class_g_ft_1_1_block_hover_manager.html", null ],
      [ "BrushSet", "class_g_ft_1_1_brush_set.html", "class_g_ft_1_1_brush_set" ],
      [ "Channel", "class_g_ft_1_1_channel.html", "class_g_ft_1_1_channel" ],
      [ "Circle", "class_g_ft_1_1_circle.html", "class_g_ft_1_1_circle" ],
      [ "Color", "class_g_ft_1_1_color.html", "class_g_ft_1_1_color" ],
      [ "ColumnLayout", "class_g_ft_1_1_column_layout.html", "class_g_ft_1_1_column_layout" ],
      [ "DeclarativeUIManager", "class_g_ft_1_1_declarative_u_i_manager.html", "class_g_ft_1_1_declarative_u_i_manager" ],
      [ "Ellipse", "class_g_ft_1_1_ellipse.html", "class_g_ft_1_1_ellipse" ],
      [ "Event", "class_g_ft_1_1_event.html", "class_g_ft_1_1_event" ],
      [ "EventMonitor", "class_g_ft_1_1_event_monitor.html", null ],
      [ "FitCurve", "class_g_ft_1_1_fit_curve.html", "class_g_ft_1_1_fit_curve" ],
      [ "Font", "class_g_ft_1_1_font.html", "class_g_ft_1_1_font" ],
      [ "Graphics", "class_g_ft_1_1_graphics.html", "class_g_ft_1_1_graphics" ],
      [ "GraphInterface", "class_g_ft_1_1_graph_interface.html", "class_g_ft_1_1_graph_interface" ],
      [ "GridLayout", "class_g_ft_1_1_grid_layout.html", "class_g_ft_1_1_grid_layout" ],
      [ "KeyboardEvent", "class_g_ft_1_1_keyboard_event.html", "class_g_ft_1_1_keyboard_event" ],
      [ "KeyboardEventMonitor", "class_g_ft_1_1_keyboard_event_monitor.html", null ],
      [ "KeyPressEvent", "class_g_ft_1_1_key_press_event.html", null ],
      [ "KeyPressEventMonitor", "class_g_ft_1_1_key_press_event_monitor.html", "class_g_ft_1_1_key_press_event_monitor" ],
      [ "KeyReleaseEvent", "class_g_ft_1_1_key_release_event.html", null ],
      [ "KeyReleaseEventMonitor", "class_g_ft_1_1_key_release_event_monitor.html", "class_g_ft_1_1_key_release_event_monitor" ],
      [ "Layout", "class_g_ft_1_1_layout.html", "class_g_ft_1_1_layout" ],
      [ "Line", "class_g_ft_1_1_line.html", "class_g_ft_1_1_line" ],
      [ "Matrix", "class_g_ft_1_1_matrix.html", "class_g_ft_1_1_matrix" ],
      [ "MouseButtonEvent", "class_g_ft_1_1_mouse_button_event.html", "class_g_ft_1_1_mouse_button_event" ],
      [ "MouseButtonEventMonitor", "class_g_ft_1_1_mouse_button_event_monitor.html", null ],
      [ "MouseButtonPressEvent", "class_g_ft_1_1_mouse_button_press_event.html", null ],
      [ "MouseButtonPressEventMonitor", "class_g_ft_1_1_mouse_button_press_event_monitor.html", "class_g_ft_1_1_mouse_button_press_event_monitor" ],
      [ "MouseButtonReleaseEvent", "class_g_ft_1_1_mouse_button_release_event.html", null ],
      [ "MouseButtonReleaseEventMonitor", "class_g_ft_1_1_mouse_button_release_event_monitor.html", "class_g_ft_1_1_mouse_button_release_event_monitor" ],
      [ "MouseEvent", "class_g_ft_1_1_mouse_event.html", "class_g_ft_1_1_mouse_event" ],
      [ "MouseEventMonitor", "class_g_ft_1_1_mouse_event_monitor.html", null ],
      [ "MouseMoveEvent", "class_g_ft_1_1_mouse_move_event.html", null ],
      [ "MouseMoveEventMonitor", "class_g_ft_1_1_mouse_move_event_monitor.html", "class_g_ft_1_1_mouse_move_event_monitor" ],
      [ "MouseWheelEvent", "class_g_ft_1_1_mouse_wheel_event.html", "class_g_ft_1_1_mouse_wheel_event" ],
      [ "MouseWheelEventMonitor", "class_g_ft_1_1_mouse_wheel_event_monitor.html", "class_g_ft_1_1_mouse_wheel_event_monitor" ],
      [ "Path", "class_g_ft_1_1_path.html", "class_g_ft_1_1_path" ],
      [ "PenSet", "class_g_ft_1_1_pen_set.html", "class_g_ft_1_1_pen_set" ],
      [ "PixelMap", "class_g_ft_1_1_pixel_map.html", "class_g_ft_1_1_pixel_map" ],
      [ "PlanEvent", "class_g_ft_1_1_plan_event.html", null ],
      [ "Point", "class_g_ft_1_1_point.html", "class_g_ft_1_1_point" ],
      [ "Polygon", "class_g_ft_1_1_polygon.html", "class_g_ft_1_1_polygon" ],
      [ "RadioManager", "class_g_ft_1_1_radio_manager.html", "class_g_ft_1_1_radio_manager" ],
      [ "Rect", "class_g_ft_1_1_rect.html", "class_g_ft_1_1_rect" ],
      [ "RoundRect", "class_g_ft_1_1_round_rect.html", "class_g_ft_1_1_round_rect" ],
      [ "RowLayout", "class_g_ft_1_1_row_layout.html", "class_g_ft_1_1_row_layout" ],
      [ "Signal", "class_g_ft_1_1_signal.html", "class_g_ft_1_1_signal" ],
      [ "Signal< void >", "class_g_ft_1_1_signal_3_01void_01_4.html", "class_g_ft_1_1_signal_3_01void_01_4" ],
      [ "Size", "class_g_ft_1_1_size.html", "class_g_ft_1_1_size" ],
      [ "TextInputEvent", "class_g_ft_1_1_text_input_event.html", "class_g_ft_1_1_text_input_event" ],
      [ "TextInputEventMonitor", "class_g_ft_1_1_text_input_event_monitor.html", "class_g_ft_1_1_text_input_event_monitor" ],
      [ "TextSet", "class_g_ft_1_1_text_set.html", "class_g_ft_1_1_text_set" ],
      [ "Texture", "class_g_ft_1_1_texture.html", "class_g_ft_1_1_texture" ],
      [ "Window", "class_g_ft_1_1_window.html", "class_g_ft_1_1_window" ]
    ] ],
    [ "Client", "class_client.html", null ],
    [ "Client< TCP >", "class_client_3_01_t_c_p_01_4.html", "class_client_3_01_t_c_p_01_4" ],
    [ "Client< UDP >", "class_client_3_01_u_d_p_01_4.html", "class_client_3_01_u_d_p_01_4" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Server", "class_server.html", null ],
    [ "Server< TCP >", "class_server_3_01_t_c_p_01_4.html", "class_server_3_01_t_c_p_01_4" ],
    [ "Server< UDP >", "class_server_3_01_u_d_p_01_4.html", "class_server_3_01_u_d_p_01_4" ],
    [ "SocketInit", "struct_socket_init.html", "struct_socket_init" ]
];